version: '2.1'
orbs:
  slack: circleci/slack@4.1
  terraform: circleci/terraform@3.0.0
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "test my app"
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "deployed"
      - slack/notify:
          event: fail
          mentions: '@caal'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  terraform-gcp:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - run:
          command: cat $HOME/.terraformrc
          name: Check Terraform token
      - terraform/fmt:
          path: .
      - terraform/validate:
          path: .
      - terraform/init:
          backend_config_file: backend.hcl
          path: .
      - terraform/plan:
          backend_config_file: backend.hcl
          path: .
workflows:
  deploy-gcp-project:
    jobs:
      - terraform-gcp
#      - test
#      - slack/on-hold:
#          context: slack-secrets
#          requires:
#            - test
#      - pause_workflow:
#          requires:
#            - test
#            - slack/on-hold
#          type: approval
#      - deploy:
#          context: slack-secrets
#          requires:
#            - pause_workflow
